version: '2'

services:

  rabbitmq:

    image: luiscoms/openshift-rabbitmq

    environment:

      # RABBITMQ_NODENAME: "rabbit@example.com"

      RABBITMQ_DEFAULT_VHOST: "example"

      RABBITMQ_ERLANG_COOKIE: 'secret cookie here'

      RABBITMQ_DEFAULT_USER: user

      RABBITMQ_DEFAULT_PASS: password

    volumes: ["./data:/var/lib/rabbitmq"]

    ports:

      # - 8080:15672

      - 15672

      - 5672

      - 25672
